var foodDIY=[
	{id:1,img:'img/foods/diy1.jpg',title:'驴打滚',abstract:'来保定上大学第一年，在街上看到驴打滚，那是第一次吃驴打滚，吃起来软软的，甜甜的，从此只要上街就会买一块驴打滚，满足味蕾的对美食的贪恋。今天去街上看到驴打滚，一秒钟决定要尝试自己做，才有了今天的驴打滚！',content:'来保定上大学第一年，在街上看到驴打滚，那是第一次吃驴打滚，吃起来软软的，甜甜的，从此只要上街就会买一块驴打滚，满足味蕾的对美食的贪恋。今天去街上看到驴打滚，一秒钟决定要尝试自己做，才有了今天的驴打滚！',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:2,img:'img/foods/diy2.jpg',title:'广东的味道——肠粉',abstract:' 关于广式肠粉的起源，目前似乎还没有统一的说法，据说早在清代末期，广州街头上就能听到卖肠粉的叫卖声。也有传说是乾隆皇帝游江南那会儿，被纪晓岚拐骗去粤西吃肠粉，当即赞不绝口，并乘兴说：“这米粉有点像猪肠子”，所以就叫肠粉了。',content:'',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:3,img:'img/foods/diy3.jpg',title:'鱼茸虾米萝卜糕',abstract:'萝卜糕是款非常广式的点心，通常配方都是米粉，萝卜、腊味之类的配搭，这次配的是鲮鱼肉，做出的萝卜糕也是款美味点心。',content:'',putDate:'2014-01-03',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:4,img:'img/foods/diy4.jpg',title:'喜饼',abstract:'喜饼是山东特色面食之一，它是由面粉、鸡蛋、糖、油等制作而成，因此营养也是相当丰富。第一次做它就给了我一份惊喜，因为没想到这饼会这么好吃。喜饼入口，外皮酥脆里面喧软、嫩滑，还带着浓浓的蛋香、奶香，实在让人欲罢不能，有种吃不够的感觉哈。',content:'',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:5,img:'img/foods/diy5.jpg',title:'狼牙土豆',abstract:'土豆是我们日常生活中很常见的食材,做法也丰富多彩,大家最为熟悉的应该就是薯条,但身为四川人,不爱薯条独独钟,这狼！牙！土！豆！,从小吃到大,这是街头巷尾都能找到的美味,现炸现卖,又便宜，又美味,被称为"夜市小吃之王",做法简单快捷好吃的秘诀就在酱汁里',content:'',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'},
	{id:6,img:'img/foods/diy6.jpg',title:'牛肉鸡蛋肠粉#樱花味道#',abstract:'肠粉是广东的一道有名的小吃，口感劲道绵软，第一次品尝就被他征服，以至于从广东回来好几年了，家人还一直念念不忘。很偶然得知竟然还有专门的粉，立刻实验了下，操作非常简单，按照说明方法配置好酱汁，蒸熟后淋上酱汁简单拌拌就好了，简单还方便哦。口感相当好呢。',content:'',putDate:'2017-06-05',see:'50',author:'admin',star:'<i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i><i class="glyphicon glyphicon-star"></i>'}
]

